---
title: "SAINT analysis"
author: "www.databrew.cc"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: "hide"
---


```{r setup, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               # echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.width = 9.64,
               fig.height = 5.9,
               fig.path = 'figures/')
```

```{r}
## Load libraries
library(ggplot2)
library(lubridate)
library(dplyr)
library(ggplot2)
library(sp)
library(raster)
library(viridis)
library(ggthemes)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(RColorBrewer)
library(readr)
library(zoo)
library(tidyr)
library(formattable)
library(sparkline)
library(mapdeck)
library(rayshader)
options(scipen = '999')
theme_set(databrew::theme_simple())
```

```{r}
# url of saint cts
url_saint <- 'https://docs.google.com/spreadsheets/d/1vOft0SKHIwxd1VQHB4P1eeQuL8fWoAz9geMP1FXZtVQ/edit?ts=5f5de37b#gid=1000624470'
```